name: Ruby

on: 
  push:
    branches:
      - master

permissions:
  contents: read

defaults:
  run:
    working-directory: rubocop-airbnb

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: # use bundler 2.3 for ruby versions < 2.6 (https://bundler.io/compatibility.html)
        - ruby-version: 2.6
          bundler-version: latest
        - ruby-version: 2.7
          bundler-version: latest
        - ruby-version: 3.0
          bundler-version: latest
        - ruby-version: 3.1
          bundler-version: latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler: ${{ matrix.bundler-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        working-directory: rubocop-airbnb
    - name: Run rspec
      run: bundle exec rspec
    - name: Run rubocop
      run: bundle exec rubocop --config .rubocop.yml --fail-fast -d


